//Test Case ID: Test22
describe('Builds a set with only complete flashcards', () => {
    it("checks that a set with only completed flashcards are created when a new set is made while there are empty flashcard input fields", () => {
        cy.visit('http://localhost:3000/')

        cy.get('[placeholder="Username"]').type(Cypress.env("test1_username"))
        cy.get('[placeholder="Password"]').type(Cypress.env("test1_password"))
        cy.get('.amplify-button').contains("Sign in").click()
        cy.wait(2000)
        cy.visit('http://localhost:3000/create/set')
        cy.get('[placeholder="Set Name"]').type("SetFor22")
        cy.get('[placeholder="Description"]').type("Test Description!!")
        cy.get('[placeholder="Title"]').last().type("A")
        cy.get('[placeholder="Definition"]').last().type("1")
        cy.contains("Add Flashcard").click()
        cy.get('[placeholder="Title"]').last().type("B")
        cy.get('[placeholder="Definition"]').last().type("2")
        cy.contains("Add Flashcard").click()
        cy.contains("Add Flashcard").click()
        cy.contains("Add Flashcard").click()
        cy.get('[type="submit"').click()
        cy.contains("ID:").should("exist")
        cy.contains("Name: SetFor22").should("exist")
        cy.contains("Description: Test Description!!").should("exist")
        cy.contains("Visibility: public").should("exist")
        cy.contains("A").should("exist")
        cy.contains("1 / 2").should("exist")
        cy.contains("Next").click()
        cy.contains("B").should("exist")
        cy.contains("2 / 2").should("exist")
        cy.wait(1000)
        cy.visit('http://localhost:3000/')
        cy.get('.deleteButton').last().click()
    })
})

//Test Case ID: Test23
describe('Builds a set with only complete flashcards when some titles are empty', () => {
    it("checks that a set with only completed flashcards are created when a new set is made while there are empty flashcard title input fields", () => {
        cy.visit('http://localhost:3000/')

        cy.get('[placeholder="Username"]').type(Cypress.env("test1_username"))
        cy.get('[placeholder="Password"]').type(Cypress.env("test1_password"))
        cy.get('.amplify-button').contains("Sign in").click()
        cy.wait(2000)
        cy.visit('http://localhost:3000/create/set')
        cy.get('[placeholder="Set Name"]').type("SetFor23")
        cy.get('[placeholder="Description"]').type("Test Description!!")
        cy.get('[placeholder="Title"]').last().type("A")
        cy.get('[placeholder="Definition"]').last().type("1")
        cy.contains("Add Flashcard").click()
        cy.get('[placeholder="Definition"]').last().type("2")
        cy.get('[type="submit"').click()
        cy.contains("ID:").should("exist")
        cy.contains("Name: SetFor23").should("exist")
        cy.contains("Description: Test Description!!").should("exist")
        cy.contains("Visibility: public").should("exist")
        cy.contains("A").should("exist")
        cy.contains("1 / 1").should("exist")
        cy.wait(1000)
        cy.visit('http://localhost:3000/')
        cy.get('.deleteButton').last().click()
    })
})

//Test Case ID: Test24
describe('Builds a set with only complete flashcards when some definitions are empty', () => {
    it("checks that a set with only completed flashcards are created when a new set is made while there are empty flashcard definition input fields", () => {
        cy.visit('http://localhost:3000/')

        cy.get('[placeholder="Username"]').type(Cypress.env("test1_username"))
        cy.get('[placeholder="Password"]').type(Cypress.env("test1_password"))
        cy.get('.amplify-button').contains("Sign in").click()
        cy.wait(2000)
        cy.visit('http://localhost:3000/create/set')
        cy.get('[placeholder="Set Name"]').type("SetFor24")
        cy.get('[placeholder="Description"]').type("Test Description!!")
        cy.get('[placeholder="Title"]').last().type("A")
        cy.get('[placeholder="Definition"]').last().type("1")
        cy.contains("Add Flashcard").click()
        cy.get('[placeholder="Title"]').last().type("B")
        cy.get('[type="submit"').click()
        cy.contains("ID:").should("exist")
        cy.contains("Name: SetFor24").should("exist")
        cy.contains("Description: Test Description!!").should("exist")
        cy.contains("Visibility: public").should("exist")
        cy.contains("A").should("exist")
        cy.contains("1 / 1").should("exist")
        cy.wait(1000)
        cy.visit('http://localhost:3000/')
        cy.get('.deleteButton').last().click()
    })
})

//Test Case ID: Test25
describe('Requires At Least One Complete Title-Def Pair', () => {
    it("displays the homepage with the welcome message and the user's name", () => {
        cy.visit('http://localhost:3000/')

        cy.get('[placeholder="Username"]').type(Cypress.env("test1_username"))
        cy.get('[placeholder="Password"]').type(Cypress.env("test1_password"))
        cy.get('.amplify-button').contains("Sign in").click()
        cy.wait(2000)
        cy.visit('http://localhost:3000/create/set')
        cy.get('[placeholder="Set Name"]').type("SetFromTest")
        cy.get('[placeholder="Description"]').type("Test Description!!")
        cy.get('[placeholder="Title"]').type("Test Title")
        cy.get('[placeholder="Definition"]').type("Test Def")
        cy.get('[type="submit"').click()
        cy.contains("ID:").should("exist")
        cy.contains("Name: SetFromTest").should("exist")
        cy.contains("Description: Test Description!!").should("exist")
        cy.contains("Visibility: public").should("exist")
        cy.contains("Test Title").should("exist")
        cy.wait(1000)
        cy.visit('http://localhost:3000/')
        cy.get('.deleteButton').last().click()
    })
})